on:
  schedule:
  - cron: "0 1 * * *"
name: '_stale'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GIT_PASSWORD }}
        stale-issue-label: 'stale'
        stale-issue-message: 'This issue is stale because it has been open 170 days with no activity. Remove stale label or comment or this will be closed in 10 days'
        stale-pr-label: 'stale'
        days-before-stale: 170
        days-before-close: 10
