on: 
  workflow_dispatch: 

name: 'analytics/adx/create-table/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          # WARN File could not be found: analytics/adx/create-database.md
          export ADX_TABLE=Events