on: 
  schedule: 
    - cron: '0 17 * * 2'
  workflow_dispatch: 

name: 'compute/spring-cloud/config-server/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          
          az group create --name $RESOURCE_GROUP --location $REGION
          az extension add --name spring-cloud
          
          export SPRING_CLOUD_NAME=springcloud-$RANDOM
          
          az spring-cloud create \
          --resource-group $RESOURCE_GROUP \
          --name $SPRING_CLOUD_NAME
          
          cd compute/spring-cloud/config-server
          
          az spring-cloud config-server set \
          --config-file application.yml \
          --name ${SPRING_CLOUD_NAME} \
          --resource-group ${RESOURCE_GROUP}
          
          cd ../../..
          
          
          az group delete --name $RESOURCE_GROUP --yes || true