on: 
  schedule: 
    - cron: '0 5 * * 2'
  workflow_dispatch: 

name: 'containers/acr/graalvm/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          if [[ -z $ACR_NAME ]]; then
          export ACR_NAME=acreg$RANDOM
          fi
          az acr create \
          --name $ACR_NAME \
          --resource-group $RESOURCE_GROUP \
          --sku Basic \
          --admin-enabled true
          
          cd acr/graalvm
          
          mvn package
          docker build -t builder -f Dockerfile.builder .
          docker run --rm --tty -v $PWD/../..:/mnt builder mvn -P graalvm -pl acr/graalvm clean install
          export ACR_GRAALVM_IMAGE=graalvm:latest
          
          az acr build --registry $ACR_NAME --image $ACR_GRAALVM_IMAGE .
          
          cd ../..
          
          
          export RESULT=$(az acr repository show --name $ACR_NAME --image $ACR_GRAALVM_IMAGE)
          az group delete --name $RESOURCE_GROUP --yes || true
          
          if [[ -z $RESULT ]]; then
          echo "Unable to find $ACR_GRAALVM_IMAGE image"
          exit 1
          fi