on: 
  schedule: 
    - cron: '0 6 * * 4'
  workflow_dispatch: 

name: 'cosmosdb/create-sql-leases-container/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          
          if [[ -z $COSMOSDB_NAME ]]; then
          export COSMOSDB_NAME=cosmosdb-$RANDOM
          az cosmosdb create \
          --name $COSMOSDB_NAME \
          --resource-group $RESOURCE_GROUP
          fi
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          
          if [[ -z $COSMOSDB_NAME ]]; then
          export COSMOSDB_NAME=cosmosdb-$RANDOM
          az cosmosdb create \
          --name $COSMOSDB_NAME \
          --resource-group $RESOURCE_GROUP
          fi
          
          
          if [[ -z $COSMOSDB_SQL_DATABASE ]]; then
          export COSMOSDB_SQL_DATABASE=sql-database-$RANDOM
          az cosmosdb sql database create \
          --resource-group $RESOURCE_GROUP \
          --account-name $COSMOSDB_NAME \
          --name $COSMOSDB_SQL_DATABASE
          fi
          
          
          if [[ -z $COSMOSDB_SQL_LEASES_CONTAINER ]]; then
          export COSMOSDB_SQL_LEASES_CONTAINER=sql-leases-$RANDOM
          az cosmosdb sql container create \
          --resource-group $RESOURCE_GROUP \
          --account-name $COSMOSDB_NAME \
          --database-name $COSMOSDB_SQL_DATABASE \
          --name $COSMOSDB_SQL_LEASES_CONTAINER \
          --partition-key-path '/id'
          fi
          
          
          export RESULT=$(az cosmosdb sql container show \
          --resource-group $RESOURCE_GROUP \
          --account-name $COSMOSDB_NAME \
          --database-name $COSMOSDB_SQL_DATABASE \
          --name $COSMOSDB_SQL_LEASES_CONTAINER \
          --output tsv --query id)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" == "" ]]; then
          echo "Failed to create CosmosDB SQL leases container $COSMOSDB_SQL_CONTAINER"
          exit 1
          fi