on: 
  schedule: 
    - cron: '0 6 * * 1'
  workflow_dispatch: 

name: 'cosmosdb/create/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          
          if [[ -z $COSMOSDB_ACCOUNT_NAME ]]; then
          export COSMOSDB_ACCOUNT_NAME=cosmosdb-$RANDOM
          az cosmosdb create \
          --name $COSMOSDB_ACCOUNT_NAME \
          --resource-group $RESOURCE_GROUP \
          --locations regionName=westus3 failoverPriority=0
          fi
          
          
          export RESULT=$(az cosmosdb show --name $COSMOSDB_ACCOUNT_NAME --resource-group $RESOURCE_GROUP --output tsv --query provisioningState)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != Succeeded ]]; then
          echo "Failed to create Cosmos DB account $COSMOSDB_ACCOUNT_NAME"
          exit 1
          fi