on: 
  schedule: 
    - cron: '0 6 * * 4'
  workflow_dispatch: 

name: 'cosmosdb/insert-item-into-sql-container/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          export COSMOSDB_NAME=cosmosdb-$RANDOM
          
          az cosmosdb create \
          --name $COSMOSDB_NAME \
          --resource-group $RESOURCE_GROUP
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          export COSMOSDB_NAME=cosmosdb-$RANDOM
          
          az cosmosdb create \
          --name $COSMOSDB_NAME \
          --resource-group $RESOURCE_GROUP
          export COSMOSDB_SQL_DATABASE=sql-database-$RANDOM
          
          az cosmosdb sql database create \
          --resource-group $RESOURCE_GROUP \
          --account-name $COSMOSDB_NAME \
          --name $COSMOSDB_SQL_DATABASE
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          export COSMOSDB_NAME=cosmosdb-$RANDOM
          
          az cosmosdb create \
          --name $COSMOSDB_NAME \
          --resource-group $RESOURCE_GROUP
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          export COSMOSDB_NAME=cosmosdb-$RANDOM
          
          az cosmosdb create \
          --name $COSMOSDB_NAME \
          --resource-group $RESOURCE_GROUP
          export COSMOSDB_SQL_DATABASE=sql-database-$RANDOM
          
          az cosmosdb sql database create \
          --resource-group $RESOURCE_GROUP \
          --account-name $COSMOSDB_NAME \
          --name $COSMOSDB_SQL_DATABASE
          export COSMOSDB_SQL_CONTAINER=sql-container-$RANDOM
          
          az cosmosdb sql container create \
          --resource-group $RESOURCE_GROUP \
          --account-name $COSMOSDB_NAME \
          --database-name $COSMOSDB_SQL_DATABASE \
          --name $COSMOSDB_SQL_CONTAINER \
          --partition-key-path '/id'
          
          cd cosmosdb/insert-item-into-sql-container
          
          mvn clean install
          export COSMOSDB_ENDPOINT=$(az cosmosdb show --resource-group $RESOURCE_GROUP \
          --name $COSMOSDB_NAME --output tsv --query documentEndpoint)
          
          export COSMOSDB_MASTER_KEY=$(az cosmosdb keys list --name $COSMOSDB_NAME \
          --resource-group $RESOURCE_GROUP --output tsv --query primaryMasterKey)
          
          export RESULT=$(java -jar target/insert-item.jar)
          cd ../..
          
          
          az group delete --name $RESOURCE_GROUP --yes || true
          
          if [[ "$RESULT" != "Item was added" ]]; then
          echo "Unable to insert item into $COSMOSDB_SQL_CONTAINER"
          exit 1
          fi