on: 
  schedule: 
    - cron: '0 1 * * 5'
  workflow_dispatch: 

name: 'databases/mssql/create/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          export MSSQL_NAME=mssql-$RANDOM
          export MSSQL_USERNAME=mssql
          export MSSQL_PASSWORD=p#ssw0rd-$RANDOM
          if [[ -z $MSSQL_NAME ]]; then
          export MSSQL_NAME=mssql-$RANDOM
          export MSSQL_USERNAME=mssql
          export MSSQL_PASSWORD=p#ssw0rd-$RANDOM
          fi
          az sql server create \
          --admin-user $MSSQL_USERNAME \
          --admin-password $MSSQL_PASSWORD \
          --name $MSSQL_NAME \
          --resource-group $RESOURCE_GROUP
          
          az group delete --name $RESOURCE_GROUP --yes || true