on: 
  schedule: 
    - cron: '0 3 * * 2'
  workflow_dispatch: 

name: 'functions/java/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          
          curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
          sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
          sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
          sudo apt-get update
          sudo apt-get install azure-functions-core-tools-3
          func
          
          
          cd functions/java
          mkdir .mvn
          echo "-ntp" > .mvn/maven.config
          
          export FUNCTIONS_JAVA=functions-java-$RANDOM
          mvn -DappName=$FUNCTIONS_JAVA -DresourceGroup=$RESOURCE_GROUP package
          mvn -DappName=$FUNCTIONS_JAVA  -DresourceGroup=$RESOURCE_GROUP \
          clean package azure-functions:deploy
          echo `az functionapp show \
          --resource-group $RESOURCE_GROUP \
          --name $FUNCTIONS_JAVA \
          --query hostNames \
          --output tsv`/api/helloworld
          
          cd ../..