name: merge_into_integration
on:
  schedule:
    - cron: '0 0 * * *'  
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GIT_PASSWORD }}
    - name: Merge into integration branch
      run: |
        git checkout integration
        git merge main || true
        git push
