on: 
  workflow_dispatch: 

name: 'postgresql/load-your-postgresql-database-with-data/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          az group create --name $RESOURCE_GROUP --location $REGION
          export DELETE_AFTER=$(( `date +%s` + 7200))
          az group update --name $RESOURCE_GROUP --set tags.'DeleteAfter'="$DELETE_AFTER"
          if [[ -z $POSTGRESQL_NAME ]]; then
          export POSTGRESQL_NAME=postgresql-$RANDOM
          export POSTGRESQL_USERNAME=postgresql
          export POSTGRESQL_PASSWORD=p#ssw0rd-$RANDOM
          fi
          az postgres server create \
          --admin-user $POSTGRESQL_USERNAME \
          --admin-password $POSTGRESQL_PASSWORD \
          --name $POSTGRESQL_NAME \
          --resource-group $RESOURCE_GROUP \
          --sku B_Gen5_1 \
          --ssl-enforcement Disabled
          export LOCAL_IP=`curl -s whatismyip.akamai.com`
          
          az postgres server firewall-rule create \
          --resource-group $RESOURCE_GROUP \
          --server $POSTGRESQL_NAME \
          --name AllowMyLocalIP \
          --start-ip-address $LOCAL_IP \
          --end-ip-address $LOCAL_IP
          
          cd postgresql/load-your-postgresql-database-with-data
          
          export POSTGRESQL_DNS_NAME=`az postgres server show \
          --resource-group $RESOURCE_GROUP \
          --name $POSTGRESQL_NAME \
          --query fullyQualifiedDomainName \
          --output tsv`
          
          export POSTGRESQL_CLIENT_USERNAME="$POSTGRESQL_USERNAME@$POSTGRESQL_NAME"
          
          PGPASSWORD=$POSTGRESQL_PASSWORD psql --host=$POSTGRESQL_DNS_NAME --port=5432 --username $POSTGRESQL_CLIENT_USERNAME --dbname=postgres --file load.sql
          
          cd ../..
          
          
          az group delete --name $RESOURCE_GROUP --yes || true