on: 
  schedule: 
    - cron: '25 13 * * 5'
  workflow_dispatch: 

name: 'security/keyvault/add-secret/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          
          az group create --name $RESOURCE_GROUP --location $REGION
          
          if [[ -z $RESOURCE_GROUP ]]; then
          export RESOURCE_GROUP=java-on-azure-$RANDOM
          fi
          export REGION=westus2
          
          az group create --name $RESOURCE_GROUP --location $REGION
          KEYVAULT_NAME="keyvault-$RANDOM"
          
          az keyvault create \
          --resource-group $RESOURCE_GROUP \
          --name $KEYVAULT_NAME
          az keyvault secret set \
          --name mySecret \
          --value mySecretValue \
          --vault-name $KEYVAULT_NAME
          
          export RESULT=$(az keyvault secret show --name mySecret --vault $KEYVAULT_NAME --query value --output tsv)
          if [[ "$RESULT" != "mySecretValue" ]]; then
          echo 'Secret was not properly set'
          az group delete --name $RESOURCE_GROUP --yes || true
          exit 1
          fi
          
          az group delete --name $RESOURCE_GROUP --yes || true