on: 
  schedule: 
    - cron: '0 0 * * 5'
  workflow_dispatch: 

name: 'servicebus/create/README.md'
jobs: 
  validate: 
    runs-on: 'ubuntu-latest'
    steps: 
      - uses: 'azure/login@v1'
        with: 
          allow-no-subscriptions: 'true'
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - uses: 'actions/checkout@v2'
      - run: | 
          # WARN File could not be found: servicebus/group/create/README.md
          export SERVICE_BUS=service-bus-$RANDOM
          az servicebus namespace create \
          --resource-group $RESOURCE_GROUP \
          --name $SERVICE_BUS \
          --sku Premium \
          --location $REGION
          
          export RESULT=$(az servicebus namespace show --resource-group $RESOURCE_GROUP --name $SERVICE_BUS --query provisioningState --output tsv)
          az group delete --name $RESOURCE_GROUP --yes || true
          if [[ "$RESULT" != Succeeded ]]; then
          exit 1
          fi